### ISSUE TITLE
tracking issue: trident refactor

### ISSUE THREAD

**Issue by fdschmidt93** [fdschmidt93/trident#11]
I'm starting to refactor trident (and later on trident-xtreme): I'll step by step clean up and better document the core `trident` functionality. This involves, per module

- Refactoring code to deduplicate and simplify logic
- Rigorous type checking and hints, s.t. Pyright does not complain
- Exhaustive docstrings and code comments

- [x] `EvalMixIn`: #10 
- [x] `TridentDataModule`: #12 
- [ ] `TridentModule` #13 
- [ ] `OptimizerMixin`
- [ ] trident helpers (functions that hierarchically join Hydra configuration for datasets, dataloader, metrics, etc.)

I also want to add further tests and associated documentation

- [x] Adding documentation to current tests #10
- [ ] Documentation for
    - [ ] `EvalMixIn`: in progress
    - [ ] `TridentDataModule`: in progress
    - [ ] `TridentDataset`: in progress
    - [ ] `OptimizerMixin`: TBD
    - [ ]  helpers: TBD
- [ ] Add further tests
    - [x] Many validation and test configurations explicitly #10
    - [ ] Maybe more?
- [ ] Add CI for various checks (types, code style, etc.)

The tests for the time being will focus on simple flow of trivial trident configs. Later on, we might want to have CI check actual toy models that should always yield a guaranteed metric.

Eventually, I want to polish `trident` documentation for release on a `github.io` page.
- [ ] Sphinxify documentation
- [ ] Re-setup docgen job

**Comment by fdschmidt93** [comment]
Completed.
